# Generated by Django 4.0.4 on 2022-04-29 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='lust_name',
            new_name='last_name',
        ),
    ]
