# Generated by Django 4.0.4 on 2022-05-04 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_group_student_teacher_groupstudents_group_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupstudents',
            options={'verbose_name': 'Group student', 'verbose_name_plural': 'GroupStudents'},
        ),
        migrations.AddField(
            model_name='groupstudents',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='project.student'),
        ),
    ]
